openapi: 3.0.0
info:
  title: test
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /autori:
    get:
      summary: ''
      operationId: get-autori
      responses:
        '200':
          description: OK
components:
  schemas:
    Autore:
      description: ''
      type: object
      properties:
        id:
          type: number
        nome:
          type: string
          minLength: 1
        cognome:
          type: string
          minLength: 1
      required:
        - id
        - nome
        - cognome
      x-examples:
        Joanne Rowling:
          id: 1000
          nome: Joanne
          cognome: Rowling
