# Generated by Django 3.1.2 on 2020-12-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menù',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_modifica', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menù',
                'verbose_name_plural': 'Menù',
            },
        ),
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('menù', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.menù')),
            ],
            options={
                'verbose_name': 'Sezione',
                'verbose_name_plural': 'Sezioni',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('indirizzo', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=200)),
                ('menù', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.menù')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('prezzo', models.FloatField()),
                ('ingredienti', models.CharField(max_length=400)),
                ('image_url', models.FileField(upload_to='')),
                ('altro', models.TextField(blank=True, default='')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.sezione')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimenti',
            },
        ),
    ]
